
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STUDENT
 */
public class add_book extends javax.swing.JFrame {

    /**
     * Creates new form add_book
     */
    public add_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        t1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(210, 22, 137, 40);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 24, 150, 50);

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Author");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 70, 130, 50);

        t3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18));
        getContentPane().add(t3);
        t3.setBounds(210, 70, 137, 40);

        t2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18));
        getContentPane().add(t2);
        t2.setBounds(210, 122, 137, 40);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Title ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 130, 50);

        c1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 51, 51));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volume Number", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        getContentPane().add(c1);
        c1.setBounds(210, 172, 137, 50);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Volume No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 168, 130, 60);

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Publisher");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 228, 130, 50);

        t4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18));
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(210, 232, 137, 40);

        t5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18));
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(210, 280, 137, 40);

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Cost");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 270, 130, 50);

        jButton6.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 51));
        jButton6.setText("Add Book");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 340, 150, 40);

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24));
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 340, 100, 40);

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Exit");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 340, 90, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gettyimages-591811718-612x612.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-16, -10, 610, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        String con_len=t1.getText();//con_len:-length of book id
        if (con_len.length()==4)
            evt.consume();
}//GEN-LAST:event_t1KeyTyped

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String id,title,author,cost,publ,d;//d is volume_no.and publ is publisher
        id=t1.getText();
        title=t2.getText();
        author=t3.getText();
        publ=t4.getText();
        cost=t5.getText();
        d=(String) c1.getSelectedItem();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this,"member id not entered!!!");
        } else if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Title not entered!!!");
        } else if(author.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Author not entered!!!");
        } else if(cost.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Cost not entered!!!");
        } else if(publ.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Publisher not entered!!!");
        } else if(d.equalsIgnoreCase("Volume Number")) {
            JOptionPane.showMessageDialog(this,"Volume Number not entered!!!");
        }

        else {
            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                        DriverManager.getConnection
                        ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                String query="INSERT INTO books VALUES('"+id+"','"+title+"','"+author+"','"+d+"','"+publ+"','"+cost+"','available');";
                stm.executeUpdate(query);

            }catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            c1.setSelectedItem("Volume Number");

        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t4KeyTyped

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_t4KeyPressed

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        // TODO add your handling code here:
        String con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
            evt.consume();
        if (con_len.length()==10)
            evt.consume();
}//GEN-LAST:event_t5KeyTyped

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new a1().setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
