
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nothing
 */
public class admin_login extends javax.swing.JFrame {
  public static String id="";
    /**
     * Creates new form admin_login
     */
    public admin_login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        r1 = new javax.swing.JCheckBox();
        t5 = new javax.swing.JTextField();
        r2 = new javax.swing.JCheckBox();
        t4 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });

        jLabel1.setText("Employee Id");

        jLabel2.setText("Password");

        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Employee Id");

        jLabel4.setText("Password");

        jLabel5.setText("Aadhar card no.");

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });

        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });

        jButton3.setText("sign up");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        r1.setText("show password");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });

        r2.setText("show password");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });

        jButton2.setText("If you are admin click here");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r1))
                                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel5)))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(t4)
                                            .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)
                                        .addComponent(r2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(r1))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(t2)
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(r2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(t5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(97, 97, 97)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String empid= t1.getText();
        String password= t2.getText();
        String c="n";
        
          try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from tlogin where empid='"+empid+"'and password='"+password+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
              
                 

                 
         
c="yes";


 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no account");
         }     
     
        
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
         
          
          
         if(c.equals("yes"))
         {
          try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    Statement stmt = (Statement) con.createStatement();
                    
                    String query="insert into login values(null,now(),now(),null,null,'"+empid+"');";
                    stmt.executeUpdate(query);
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
         
        
         
        
         try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select id from login where logindate= date(now()) and logintime =time(now());";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
               admin_login.id = rs.getString("id");
               new welcome().setVisible(true);
       this.dispose();
        
        
                 

 Found++; 
             }
              
         if(Found==0)
         {
         
        
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
         
        
   
       
        
         }
      
                                        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String empid = t3.getText();
        String password = t4.getText();
        String aadhar= t5.getText();
        String c="no";
        
        
        
        try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from teacher where empid='"+empid+"'and aadhar='"+aadhar+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
 Found++; 
 c="yes";
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "wrong aadhar or employee id");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
        if(c.equals("yes"))
        {
        try
          {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    Statement stmt = (Statement) con.createStatement();
                    
                    String query="insert into tlogin values('"+empid+"','"+password+"','"+aadhar+"');";
                    stmt.executeUpdate(query);
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
         
        
        
        
        
        
        
        
        
        }
        
        
         
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        if(r1.isSelected()==true)
        {
        t2.setEchoChar((char)0);
        
        
        }
        else if(r1.isSelected()==false){
        
      t2.setEchoChar('*');
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
        
         if(r2.isSelected()==true)
        {
        t4.setEchoChar((char)0);
        
        
        }
        else if(r2.isSelected()==false){
        
      t4.setEchoChar('*');
        }
        
        
    }//GEN-LAST:event_r2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id= JOptionPane.showInputDialog(this, "enter your id");
        String pass= JOptionPane.showInputDialog(this,"enter password");
        if(id.equals("prakhar")&&pass.equals("gumshuda"))
        {
        JOptionPane.showMessageDialog(this,"Hello prakhar");
        new admin_welcome().setVisible(true);
        this.dispose();
        
        
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
         String con_len=t1.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==5)
           evt.consume();
    }//GEN-LAST:event_t1KeyTyped

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
        
         String con_len=t2.getText();//con_len:- contact length
        char character=evt.getKeyChar();
     
       if (con_len.length()==20)
           evt.consume();
    }//GEN-LAST:event_t2KeyTyped

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:
          String con_len=t4.getText();//con_len:- contact length
        char character=evt.getKeyChar();
     
       if (con_len.length()==20)
           evt.consume();
    }//GEN-LAST:event_t4KeyTyped

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
        // TODO add your handling code here:
        String con_len=t3.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==5)
           evt.consume();
    }//GEN-LAST:event_t3KeyTyped

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        // TODO add your handling code here:
        String con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox r1;
    private javax.swing.JCheckBox r2;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JPasswordField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
