
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class fees_add extends javax.swing.JFrame {

    /**
     * Creates new form fees
     */
    public fees_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        t1.setFont(new java.awt.Font("Arimo", 1, 16)); // NOI18N
        t1.setForeground(new java.awt.Color(50, 45, 45));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("Enter the Sr.No. and Press Enter");
        t1.setEnabled(false);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(20, 50, 310, 36);

        jLabel2.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 60, 70, 22);

        t2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        t2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        getContentPane().add(t2);
        t2.setBounds(480, 60, 127, 26);

        jLabel3.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Class");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 60, 70, 22);

        t3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        t3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        getContentPane().add(t3);
        t3.setBounds(750, 60, 127, 26);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        r1.setForeground(new java.awt.Color(0, 0, 51));
        r1.setText("Installment 1");
        r1.setEnabled(false);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(30, 160, 130, 25);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        r2.setForeground(new java.awt.Color(0, 0, 51));
        r2.setText("Insallment 2");
        r2.setEnabled(false);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(310, 160, 120, 25);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        r3.setForeground(new java.awt.Color(0, 0, 51));
        r3.setText("Insallment 3");
        r3.setEnabled(false);
        getContentPane().add(r3);
        r3.setBounds(630, 160, 120, 25);

        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        r4.setForeground(new java.awt.Color(0, 0, 51));
        r4.setText("Installment 4");
        r4.setEnabled(false);
        getContentPane().add(r4);
        r4.setBounds(920, 160, 130, 25);

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Update");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, null, null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 220, 160, 40);

        t5.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t5.setForeground(new java.awt.Color(0, 51, 51));
        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t5);
        t5.setBounds(450, 320, 120, 28);

        t4.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t4.setForeground(new java.awt.Color(0, 51, 51));
        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t4);
        t4.setBounds(160, 320, 110, 28);

        t8.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t8.setForeground(new java.awt.Color(0, 51, 51));
        t8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t8);
        t8.setBounds(160, 390, 110, 30);

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("I Installment Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 330, 140, 17);

        jLabel8.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("I Installment Time");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 400, 130, 17);

        jLabel9.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("II Installment Time");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 400, 140, 17);

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("II Installment Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 330, 140, 17);

        t9.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t9.setForeground(new java.awt.Color(0, 51, 51));
        t9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t9);
        t9.setBounds(450, 390, 120, 30);

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("III Installment Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 330, 150, 17);

        jLabel10.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("III Installment Time");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(610, 400, 140, 17);

        t6.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t6.setForeground(new java.awt.Color(0, 51, 51));
        t6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t6);
        t6.setBounds(760, 320, 110, 30);

        t10.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t10.setForeground(new java.awt.Color(0, 51, 51));
        t10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t10);
        t10.setBounds(760, 400, 110, 30);

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("IV Installment Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(900, 330, 140, 17);

        jLabel11.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("IV Installment Time");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(900, 400, 140, 17);

        t7.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t7.setForeground(new java.awt.Color(0, 51, 51));
        t7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7);
        t7.setBounds(1060, 320, 100, 28);

        t11.setFont(new java.awt.Font("Arimo", 2, 12)); // NOI18N
        t11.setForeground(new java.awt.Color(0, 51, 51));
        t11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t11);
        t11.setBounds(1060, 390, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-photo-316466.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-110, -130, 1370, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           String id2= admin_login.id;
        try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update login set logoutdate= now(), logouttime= now() where id = '"+id2+"';";
                    stmt.executeUpdate(query);
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
         
        
               System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        
        String srno=t1.getText();
        String fstname="";
        String lstname="";
        String clas="";
        String sec="";
        String i1="n";
        String i2="n";
        String i3="n";
        String i4="n";
        String no="";
        String it1="";
        String it2="";
        String it3="";
        String it4="";
        int instno=0;
           
        
        
        
        
        
        try
               
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from student where srno='"+srno+"';";
     ResultSet rs= stmt.executeQuery(query);
     int f=0;


         while(rs.next()) 
                    
             {
                 
                 
                 
                 
        
       fstname = rs.getString("fstname");
        lstname = rs.getString("lstname");
        
        srno = rs.getString("srno");
        
        clas =rs.getString("class");
        sec = rs.getString("sec");
f++;
             }
            if(f==0)
            {
            JOptionPane.showMessageDialog(this, "no result found");
            }
     
     
     
        }
        catch(Exception e)

        {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }
t1.setText(srno);
t2.setText(fstname+" "+lstname);
t3.setText(clas);




try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from fee where srno='"+srno+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
                 
                 
                 
                 
         
       i1 = rs.getString("d1");
        i2 = rs.getString("d2");
        
        i3 = rs.getString("d3");
        
        i4 =rs.getString("d4");
        no= rs.getString("no");
        it1= rs.getString("t1");
        it2= rs.getString("t2");
        it3= rs.getString("t3");
        it4= rs.getString("t4"); 
          
         
       



             }
              
       
        
        }
        catch(Exception e)

        {

            JOptionPane.showMessageDialog(this, e.getMessage());

   
        
    }      
              

instno= Integer.parseInt(no);

           
          System.out.println(i1);
          System.out.println(i2);
          System.out.println(i3);
          System.out.println(no);
         t4.setText(""+instno);
         if(instno==0)
         {
r1.setEnabled(true);
r2.setEnabled(false);
r3.setEnabled(false);
r4.setEnabled(false);
t4.setText("not given");
t5.setText("not given");
t6.setText("not given");
t7.setText("not given");
t8.setText("not given");
t9.setText("not given");
t10.setText("not given");
t11.setText("not given");
         

         
        
         }
         else if(instno==1)
         {
r2.setEnabled(true);
r1.setEnabled(false);
r3.setEnabled(false);
r4.setEnabled(false);
t4.setText(i1);
t5.setText("not given");
t6.setText("not given");
t7.setText("not given");
t8.setText(it1);
t9.setText("not given");
t10.setText("not given");
t11.setText("not given");



         }
        else if(instno==2)
         {
r1.setEnabled(false);
r2.setEnabled(false);
r4.setEnabled(false);
r3.setEnabled(true);
t4.setText(i1);
t5.setText(i2);
t6.setText("not given");
t7.setText("not given");
t8.setText(it1);
t9.setText(it2);
t10.setText("not given");
t11.setText("not given");


         }
         else if(instno==3)
         {
r4.setEnabled(true);
 r1.setEnabled(false);
 r2.setEnabled(false);
 r3.setEnabled(false);
 t4.setText(i1);
 t5.setText(i2);
 t6.setText(i3);
 t7.setText("not given");
 t8.setText(it1);
 t9.setText(it2);
 t10.setText(it3);
 t11.setText("not given");
 
         }
         else
         {
         r4.setEnabled(false);
 r1.setEnabled(false);
 r2.setEnabled(false);
 r3.setEnabled(false);
 t4.setText(i1);
 t5.setText(i2);
 t6.setText(i3);
 t7.setText(i4);
 t8.setText(it1);
 t9.setText(it2);
 t10.setText(it3);
 t11.setText(it4);
         
         
         
         }
         
         
         
         
         
    }//GEN-LAST:event_t1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String srno=t1.getText();
        String fstname="";
        String lstname="";
        String clas="";
        String sec="";
        String i1="n";
        String i2="n";
        String i3="n";
        String i4="n";
        int inst=0;
           
        
        



       
        
        
        
        if(r1.isSelected())
        {
        inst = 1;
        }
        else if(r2.isSelected())
        {
            inst =2;
        }
        
        
        else if(r3.isSelected())
        {
        inst=3;
        }
        
        else if(r4.isSelected())
        {
            inst=4;
        }
        else JOptionPane.showMessageDialog(this,"choose the installment to be paid");
        
        
        
        
        
        
        
        
        
      

if(inst==1)
        {
            try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update fee set d1=now(),t1=now(),no=1 where srno='"+srno+"';";
                    stmt.executeUpdate(query);
                    
                    JOptionPane.showMessageDialog(this, "fee succesfully updated");
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        }
        



if(inst==2)
{

try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update fee set d2= now(), t2=now(),no=2 where srno='"+srno+"';";
                    stmt.executeUpdate(query);
                    
                    JOptionPane.showMessageDialog(this, "fee succesfully updated");
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }


}


if(inst==3)
{

try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update fee set d3= now(), t3=now(),no=3 where srno='"+srno+"';";
                    stmt.executeUpdate(query);
                    
                    JOptionPane.showMessageDialog(this, "fee succesfully updated");
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }


}




if(inst==4)
{

try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update fee set d4= now(), t4=now(),no=4 where srno='"+srno+"';";
                    stmt.executeUpdate(query);
                    
                    JOptionPane.showMessageDialog(this, "fee succesfully updated");
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }


}
         
buttonGroup1.clearSelection();
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
        
        
         
    }//GEN-LAST:event_formWindowActivated

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t1KeyPressed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
        t1.setEnabled(true);
        t1.setText("");
        t1.requestFocus();
    }//GEN-LAST:event_t1MouseClicked

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fees_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fees_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fees_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fees_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
