
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class fees_search extends javax.swing.JFrame {

    /**
     * Creates new form fees_search
     */
    public fees_search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        r1.setForeground(new java.awt.Color(51, 0, 51));
        r1.setSelected(true);
        r1.setText("I Installment");
        r1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(110, 40, 170, 33);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        r2.setForeground(new java.awt.Color(51, 0, 51));
        r2.setText("II Installment");
        r2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(r2);
        r2.setBounds(290, 40, 180, 33);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        r3.setForeground(new java.awt.Color(51, 0, 51));
        r3.setText("III Installment");
        r3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(r3);
        r3.setBounds(480, 40, 190, 33);

        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        r4.setForeground(new java.awt.Color(51, 0, 51));
        r4.setText("IV Insallment");
        r4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(r4);
        r4.setBounds(680, 40, 180, 33);

        c1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        c1.setForeground(new java.awt.Color(51, 0, 51));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" }));
        c1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51))));
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c1MousePressed(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(10, 40, 60, 30);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 110, 110, 50);

        jTable1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 0, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No.", "Name", "Class"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 200, 650, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-photo-399160.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -280, 940, 1050);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          DefaultTableModel model = (DefaultTableModel)
jTable1.getModel();
   int rows=model.getRowCount();
 if (rows>0)
 {
 for (int i=0; i<rows; i++)
model.removeRow(0); 
 }
        int clas= c1.getSelectedIndex()+1;
       String clas1=""+clas;
       String fstname="";
       String lstname="";
       String sec="";
       String srno="";
       String no="";
       

       int k=-1;
       if(r1.isSelected())
       {
       k=0;
       }
       
       else if(r2.isSelected())
       {
       k=1;
       }
       
       else if(r3.isSelected())
       {
       k=2;
       }
       
       else if(r4.isSelected())
       {
       k=3;
       }
       else JOptionPane.showMessageDialog(this, "select installment");
       
      
           
            try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from fee, student where fee.srno = student.srno and class='"+clas1+"'and no='"+k+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
              fstname= rs.getString("fstname");
              lstname= rs.getString("lstname");
              no= rs.getString("no");
              sec= rs.getString("sec");
              srno=rs.getString("srno");
              
              model.addRow( new Object[]{srno,fstname+" "+lstname,(String)c1.getSelectedItem()+" - "+sec});
              
         
 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no name");
         }     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
   
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        // TODO add your handling code here:

      
       
    }//GEN-LAST:event_c1MouseClicked

    private void c1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MousePressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_c1MousePressed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fees_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fees_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fees_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fees_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees_search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    // End of variables declaration//GEN-END:variables
}
