
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STUDENT
 */
public class issue_book extends javax.swing.JFrame {

    /**
     * Creates new form issue_book
     */
    public issue_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        c7 = new javax.swing.JComboBox<String>();
        c6 = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox<String>();
        bb1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<String>();
        t2 = new javax.swing.JTextField();
        bb2 = new javax.swing.JCheckBox();
        t1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 360, 90, 30);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 360, 80, 30);

        c7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c7.setForeground(new java.awt.Color(0, 51, 51));
        c7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Librarian", "Admin" }));
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        getContentPane().add(c7);
        c7.setBounds(250, 300, 220, 20);

        c6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c6.setForeground(new java.awt.Color(0, 51, 51));
        c6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        getContentPane().add(c6);
        c6.setBounds(380, 250, 70, 20);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Issue Date");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 190, 130, 33);

        c5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c5.setForeground(new java.awt.Color(0, 51, 51));
        c5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(c5);
        c5.setBounds(310, 250, 60, 20);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Book ID");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 140, 130, 33);

        c3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(0, 51, 51));
        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        getContentPane().add(c3);
        c3.setBounds(380, 200, 70, 20);

        bb1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        bb1.setText("Student");
        getContentPane().add(bb1);
        bb1.setBounds(270, 80, 80, 25);

        c2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(0, 51, 51));
        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(c2);
        c2.setBounds(310, 200, 60, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Issuer");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 290, 130, 33);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("Issue");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 360, 90, 30);

        c1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 51, 51));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(c1);
        c1.setBounds(250, 200, 50, 20);

        t2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        getContentPane().add(t2);
        t2.setBounds(250, 40, 262, 20);

        bb2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        bb2.setText("Employee");
        getContentPane().add(bb2);
        bb2.setBounds(390, 80, 88, 23);

        t1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(t1);
        t1.setBounds(250, 150, 262, 16);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Return Date");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 240, 130, 33);

        c4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c4.setForeground(new java.awt.Color(0, 51, 51));
        c4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(c4);
        c4.setBounds(250, 250, 50, 20);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/books.jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String boid,soid,bid,issd,issm,issy,retd,retm,rety,issuer,issued,returnd;//bid is book id sid employee id
        int sid;
        bid=t1.getText();
        sid=Integer.parseInt(t2.getText());
        boid="";
        soid="";
        issd=(String) c1.getSelectedItem();
        issm=(String) c2.getSelectedItem();
        issy=(String) c3.getSelectedItem();
        retd=(String) c4.getSelectedItem();
        retm=(String) c5.getSelectedItem();
        rety=(String) c6.getSelectedItem();
        issuer=(String) c7.getSelectedItem();

        if (!(bb1.isSelected())&&!(bb2.isSelected()))
        {
            JOptionPane.showMessageDialog(this,"Select post!!!");
        }
        else if (bid.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"book id not entered!!!");
        }
        else if (t2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"employee id or Sr.No. not entered!!!");
        }
        else if(issd.equalsIgnoreCase("DD"))
        {
            JOptionPane.showMessageDialog(this,"Issue date not entered!!!");
        }
        else if(issm.equalsIgnoreCase("MM"))
        {
            JOptionPane.showMessageDialog(this,"Issue month not entered!!!");
        }
        else if(issy.equalsIgnoreCase("YYYY"))
        {
            JOptionPane.showMessageDialog(this,"Issue year not entered!!!");
        }
        else if(retd.equalsIgnoreCase("DD"))
        {
            JOptionPane.showMessageDialog(this,"Return date not entered!!!");
        }
        else if(retm.equalsIgnoreCase("MM"))
        {
            JOptionPane.showMessageDialog(this,"Return month not entered!!!");
        }
        else if(rety.equalsIgnoreCase("YYYY"))
        {
            JOptionPane.showMessageDialog(this,"Return year not entered!!!");
        }
        else if(Integer.parseInt(issy)>Integer.parseInt(rety))
        {
            JOptionPane.showMessageDialog(this," Incorrect return date!!!");
        }
        else if(Integer.parseInt(issy)==Integer.parseInt(rety)&&Integer.parseInt(issm)>Integer.parseInt(retm))
        {
            JOptionPane.showMessageDialog(this," Incorrect return date!!!");
        }
        else if(Integer.parseInt(issy)==Integer.parseInt(rety)&&Integer.parseInt(issm)==Integer.parseInt(retm)&&Integer.parseInt(issd)>Integer.parseInt(retd))
        {
            JOptionPane.showMessageDialog(this," Incorrect return date!!!");
        }
        else
        {
            issued=issy+"-"+issm+"-"+issd;
            returnd=rety+"-"+retm+"-"+retd;

            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                Statement stm1 = (Statement) conn.createStatement();
                String query="select * from books where book_id ='"+bid+"';";
                String query2;
                ResultSet rs=stm.executeQuery(query);
                if(rs.next())
                {
                    boid=rs.getString("availability");
                    if (boid.equalsIgnoreCase("not-avaialble"))
                    {
                        JOptionPane.showMessageDialog (this, "Sorry! Book not available!!");
                    }

                    else if (boid.equalsIgnoreCase("available"))
                    {

                        if(bb1.isSelected())
                        {
                            try

                            {
                                Class.forName("java.sql.DriverManager");
                                conn = (Connection)
                                DriverManager.getConnection
                                ("jdbc:mysql://localhost:3306/schm","root", "window");
                                stm = (Statement) conn.createStatement();
                                query="select * from sissue where srno="+sid+";";
                                rs=stm.executeQuery(query);
                                if(rs.next())
                                {
                                    soid=rs.getString("srno");
                                    JOptionPane.showMessageDialog (this, "Sorry! A Book is already issued to "+soid);
                                }
                                else
                                {
                                    try

                                    {

                                        Class.forName("java.sql.DriverManager");
                                        conn = (Connection)
                                        DriverManager.getConnection
                                        ("jdbc:mysql://localhost:3306/schm","root", "window");
                                        stm = (Statement) conn.createStatement();
                                        query="INSERT INTO Sissue VALUES("+sid+",'"+bid+"','"+issued+"','"+returnd+"','"+issuer+"');";
                                        query2 ="Update books set availability='not-available';";

                                        stm.executeUpdate(query);
                                        stm1.executeUpdate(query2);
                                    }catch(Exception e)
                                    {
                                        JOptionPane.showMessageDialog (this, e.getMessage());
                                    }
                                }
                            }catch(Exception e)
                            {
                                JOptionPane.showMessageDialog (this, e.getMessage());
                            }
                        }

                        else if(bb2.isSelected())
                        {
                            try

                            {
                                Class.forName("java.sql.DriverManager");
                                conn = (Connection)
                                DriverManager.getConnection
                                ("jdbc:mysql://localhost:3306/schm","root", "window");
                                stm = (Statement) conn.createStatement();
                                query="select * from eissue where employee="+sid+";";
                                rs=stm.executeQuery(query);
                                if(rs.next())
                                {
                                    soid=rs.getString("employee");
                                    JOptionPane.showMessageDialog (this, "Sorry! A Book is already issued to "+soid);
                                }
                                else
                                {
                                    try

                                    {

                                        Class.forName("java.sql.DriverManager");
                                        conn = (Connection)
                                        DriverManager.getConnection
                                        ("jdbc:mysql://localhost:3306/schm","root", "window");
                                        stm = (Statement) conn.createStatement();
                                        query="INSERT INTO eissue VALUES("+sid+",'"+bid+"','"+issued+"','"+returnd+"','"+issuer+"');";
                                        query2 ="Update books set availability='not-available';";
                                        stm.executeUpdate(query);
                                        stm.executeUpdate(query2);
                                    }catch(Exception e)
                                    {
                                        JOptionPane.showMessageDialog (this, e.getMessage());
                                    }
                                }
                            }catch(Exception e)
                            {
                                JOptionPane.showMessageDialog (this, e.getMessage());
                            }
                        }
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog (this, "No Such Book Found");
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }

            t1.setText("");
            t2.setText("");

            c1.setSelectedIndex(0);
            c2.setSelectedIndex(0);
            c3.setSelectedIndex(0);
            c4.setSelectedIndex(0);
            c5.setSelectedIndex(0);
            c6.setSelectedIndex(0);
            c7.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new a1().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_c7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bb1;
    private javax.swing.JCheckBox bb2;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JComboBox<String> c6;
    private javax.swing.JComboBox<String> c7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
