
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class marks_add extends javax.swing.JFrame {
DefaultListModel listModel1 = new DefaultListModel();
DefaultListModel listModal2 = new DefaultListModel();
    /**
     * Creates new form marks_add
     */
    public marks_add() {
        initComponents();
    }
public String con_len,s="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        l5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Name", "Class"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 40, 530, 200);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Class");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 70, 70, 30);

        c1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        c1.setForeground(new java.awt.Color(51, 51, 51));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(700, 70, 50, 30);

        jButton2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 280, 100, 35);

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 130, 100, 35);

        l5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(l5);
        l5.setBounds(530, 350, 83, 34);

        t5.setBackground(new java.awt.Color(51, 51, 51));
        t5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t5.setForeground(new java.awt.Color(255, 255, 255));
        t5.setBorder(new javax.swing.border.MatteBorder(null));
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t5MouseClicked(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(530, 390, 83, 30);

        l4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(l4);
        l4.setBounds(430, 350, 84, 34);

        t4.setBackground(new java.awt.Color(51, 51, 51));
        t4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t4.setForeground(new java.awt.Color(255, 255, 255));
        t4.setBorder(new javax.swing.border.MatteBorder(null));
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(430, 390, 84, 30);

        l3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(l3);
        l3.setBounds(330, 350, 83, 34);

        t3.setBackground(new java.awt.Color(51, 51, 51));
        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setBorder(new javax.swing.border.MatteBorder(null));
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t3MouseClicked(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(330, 390, 83, 30);

        l2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(l2);
        l2.setBounds(230, 350, 83, 34);

        t2.setBackground(new java.awt.Color(51, 51, 51));
        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setBorder(new javax.swing.border.MatteBorder(null));
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(230, 390, 83, 30);

        l1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(l1);
        l1.setBounds(120, 350, 83, 34);

        t1.setBackground(new java.awt.Color(51, 51, 51));
        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setBorder(new javax.swing.border.MatteBorder(null));
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(120, 390, 83, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Educational-Supplies-PPT-Backgrounds-800x600.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)
jTable1.getModel();
  int rows=model.getRowCount();
 if (rows>0)
 {
 for (int i=0; i<rows; i++)
model.removeRow(0); 
 }
        int clas=c1.getSelectedIndex()+1;
        String clas1=""+clas;
        String fstname= "";
        String lstname="";
        String name="";
        String srno="";
        String sec="";
        
        
        
       
     try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from student where class='"+clas1+"' order by fstname;";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
               
               fstname= rs.getString("fstname");
               lstname =rs.getString("lstname");
               
               name= fstname+" "+lstname;
               srno= rs.getString("srno");
               sec= rs.getString("sec");
                model.addRow( new Object[]{srno,name,clas1+" - "+sec});

          
         

         
 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no results found");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
         
     
     
     
     
     
     
     
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
 int k=0;
        String s1= t1.getText();
        String s2= t2.getText();
        String s3= t3.getText();
        String s4= t1.getText();
        String s5= t5.getText();
        String subject="";
        String optional="";

    k= jTable1.getSelectedRow();
    System.out.println(""+k);
    
  
String srno = jTable1.getModel().getValueAt(k,0).toString();





   
        DefaultTableModel model = (DefaultTableModel)
jTable1.getModel();
        
     try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from marks where srno='"+srno+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
             s1= rs.getString("s1");
             s2= rs.getString("s2");
             s3= rs.getString("s3");
             s4= rs.getString("s4");
             s5= rs.getString("s5");
             

          
         

         
 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no results found");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
         
     
     


   l1.setText("English");
   
   if(c1.getSelectedIndex()<10)
   {
   l2.setText("Maths");
   l3.setText("Hindi");
   l4.setText("Science");
   l5.setText("Social Studies");
   
   
   }
   else
   {
   
   
       try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from subject where srno='"+srno+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
               subject= rs.getString("subject");
               optional = rs.getString("optional");

          
         

         
 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no results found");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
       l5.setText(optional);
         
       if(subject.equalsIgnoreCase("Science (maths)"))
       {
       l2.setText("Maths");
       l3.setText("Physics");
       l4.setText("Chemistry");
       
       }
     
       else if(subject.equalsIgnoreCase("Science (biology)"))
       {
       l2.setText("Biology");
       l3.setText("Physics");
       l4.setText("Chemistry");
       
       }
       
      else if(subject.equalsIgnoreCase("commerce"))
       {
       l2.setText("Accountancy");
       l3.setText("Business Studies");
       l4.setText("Economics");
       
       }
       
      else if(subject.equalsIgnoreCase("humanities"))
       {
       l2.setText("Geography");
       l3.setText("History");
       l4.setText("Politiacal science");
       
       }
     
   
   t1.setText(s1);
   t2.setText(s2);
   t3.setText(s3);
   t4.setText(s4);
   t5.setText(s5);
   
   
   
   
   
   
   
   
   }
 
    }//GEN-LAST:event_jTable1MouseClicked

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyPressed

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
//     try{
        double d; 
        con_len=t1.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
//       s=s+con_len;
       
     
      if(con_len.length()>=1)
      {
       d=Double.parseDouble(con_len);
       if(d>10)
       {
       evt.consume();   
       }
      }
//      if(d>100)JOptionPane.showMessageDialog(null, d);
//     }catch(Exception e)
//     {
//         
//     }
    }//GEN-LAST:event_t1KeyTyped

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        // TODO add your handling code here:
         con_len=t2.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
       
    }//GEN-LAST:event_t3KeyPressed

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:
         con_len=t4.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t4KeyTyped

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
        // TODO add your handling code here:
         // TODO add your handling code here:
         con_len=t3.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t3KeyTyped

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
             con_len=t2.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t2KeyTyped

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        // TODO add your handling code here:
             con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t5KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int k=0;
        String s1= t1.getText();
        String s2= t2.getText();
        String s3= t3.getText();
        String s4= t1.getText();
        String s5= t5.getText();
        String subject="";
        String optional="";

    k= jTable1.getSelectedRow();
    System.out.println(""+k);
    
  
String srno = jTable1.getModel().getValueAt(k,0).toString();
        
        
         try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update marks set s1='"+s1+"',s2='"+s2+"',s3='"+s3+"',s4='"+s4+"',s5='"+s5+"' where srno='"+srno+"';";
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(this,"Marks updated successfully");
                    
                   
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }




        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
        t1.setText("");
    }//GEN-LAST:event_t1MouseClicked

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        // TODO add your handling code here:
        t2.setText("");
    }//GEN-LAST:event_t2MouseClicked

    private void t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseClicked
        // TODO add your handling code here:
        t3.setText("");
    }//GEN-LAST:event_t3MouseClicked

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
        // TODO add your handling code here:
        t4.setText("");
    }//GEN-LAST:event_t4MouseClicked

    private void t5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseClicked
        // TODO add your handling code here:
        t5.setText("");
    }//GEN-LAST:event_t5MouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marks_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marks_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marks_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marks_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marks_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
