
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class salary extends javax.swing.JFrame {

    /**
     * Creates new form salary
     */
    public salary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        t1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("Enter EmpID & Press Enter");
        t1.setEnabled(false);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(300, 60, 270, 40);

        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t2);
        t2.setBounds(120, 170, 121, 23);

        jLabel2.setFont(new java.awt.Font("Batang", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 170, 50, 20);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel5.setText("Total Days");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 60, 30);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(120, 240, 121, 29);

        jLabel4.setFont(new java.awt.Font("Batang", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Monthly Salary");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 170, 109, 17);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel6.setText("No.of Leaves");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 240, 64, 30);

        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t4);
        t4.setBounds(410, 170, 111, 23);
        getContentPane().add(t6);
        t6.setBounds(410, 240, 111, 29);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel7.setText("No.of Half Days");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 240, 75, 30);

        jLabel3.setFont(new java.awt.Font("Batang", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Designation");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 170, 82, 17);

        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t3);
        t3.setBounds(670, 170, 113, 23);
        getContentPane().add(t7);
        t7.setBounds(670, 240, 113, 29);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Calculate ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 330, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Final Amount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 390, 100, 30);

        t8.setEditable(false);
        getContentPane().add(t8);
        t8.setBounds(390, 390, 113, 29);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bb2b49af210d4b29.jpeg"))); // NOI18N
        jLabel9.setText(" ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-290, -160, 1287, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(t1.getText().isEmpty()==true)
              {
              JOptionPane.showMessageDialog(this,"enter proper employee id");
              }
        
        
      else  if(t5.getText().isEmpty()==true||t6.getText().isEmpty()==true||t7.getText().isEmpty()==true)
      {
      
      JOptionPane.showMessageDialog(this,"enter total days and leave and halfdays");}
     
      
      else{
       String empid = t1.getText();
       String fstname="";
       String lstname="";
       String post="";
       String salary = "";
       int totaldays =Integer.parseInt(t5.getText());
       int leave =Integer.parseInt(t6.getText()); ;
       int halfday  =Integer.parseInt(t7.getText());
       double finalsalary =0;
       
        double sal= 0;
      double halfdayby2= 0;
      double totalleave=0;
      double salday=0;
      double salperday=0;
      
       
      
       try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
                "root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from teacher where empid='"+empid+"';";
          ResultSet rs=  stmt.executeQuery(query);

          
          
          int Found=0;
         while(rs.next()) 
                    
             {
             
             
                 empid= rs.getString("empid");
                 salary=rs.getString("salary");
                 fstname=rs.getString("fstname");
                  lstname=rs.getString("lstname");
       post= rs.getString("post");
        
                  
           
           
         
           
               
              
        
      sal= Double.parseDouble(salary);
      halfdayby2= 0.5*halfday;
      totalleave=leave+halfdayby2;
      salday= totaldays-totalleave;
      salperday=sal/totaldays;
              
      
      if(totalleave<=1)
      {
      
      finalsalary= sal;
      
     
      }
      
else
      {
      
      finalsalary=(salday+1)*salperday;
      }
      
      t8.setText(""+Math.round(finalsalary));
      t2.setText(fstname+" "+lstname);
      t3.setText(post);
      t4.setText(salary);
      
      
      
      

         
         
         
          
         
         
         
         
                    
              Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no such emp");
         }     
     
     
     
     
          
        }
        
        
        
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
      
        

       
    
    
    
      



       
       
       
       
        
         try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="insert into salary values('"+empid+"','"+leave+"','"+salday+"','"+totaldays+"','"+halfday+"','"+Math.round(finalsalary)+"');";
                    stmt.executeUpdate(query);
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
                    
            
        }
       
       
       
       
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
       
 String empid = t1.getText();
       String fstname="";
       String lstname="";
       String post="";
       String salary = "";
    
       try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
                "root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from teacher where empid='"+empid+"';";
          ResultSet rs=  stmt.executeQuery(query);

          
          
          int Found=0;
         while(rs.next()) 
                    
             {
             
             
                 empid= rs.getString("empid");
                 salary=rs.getString("salary");
                 fstname=rs.getString("fstname");
                  lstname=rs.getString("lstname");
       post= rs.getString("post");
        
                  
           
           
         
           
               
              
    
      
      
      t2.setText(fstname+" "+lstname);
      t3.setText(post);
      t4.setText(salary);
      
      
      
      

         
         
         
          
         
         
         
         
                    
              Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no such emp");
         }     
     
     
     
     
          
        }
        
        
        
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
      
        

    }//GEN-LAST:event_t1ActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
       
        t1.requestFocus();
        t1.setText("");
          t1.setEnabled(true);
    }//GEN-LAST:event_t1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        t1.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
