
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class session_history extends javax.swing.JFrame {

    /**
     * Creates new form session_history
     */
    public session_history() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "name", "login date", "login time", "logout date", "logout time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 60, 680, 240);

        jButton1.setFont(new java.awt.Font("AngsanaUPC", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(75, 22, 6));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 410, 140, 40);

        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("Enter Emp ID & Press Enter to search for particular Employee");
        t1.setEnabled(false);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(250, 340, 330, 40);

        jButton2.setFont(new java.awt.Font("AngsanaUPC", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(75, 22, 6));
        jButton2.setText("Reset Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 410, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-photo-590493.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-250, -220, 1444, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel model = (DefaultTableModel)
jTable1.getModel();
         int rows=model.getRowCount();
 if (rows>0)
 {
 for (int i=0; i<rows; i++)
model.removeRow(0); 
 }
        String empid=t1.getText();
        String fstname= "";
        String lstname="";
        String name="";
        String logindate;
        String logintime;
        String logoutdate;
        String logouttime;
        
        
     try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from login, teacher where login.empid=teacher.empid;";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
               logindate= rs.getString("logindate");
               logintime= rs.getString("logintime");
               logoutdate= rs.getString("logoutdate");
               logouttime= rs.getString("logouttime");
               fstname= rs.getString("fstname");
               lstname =rs.getString("lstname");
               empid = rs.getString("empid");
               name= fstname+" "+lstname;

          model.addRow( new Object[]{empid,name,logindate,logintime,logoutdate,logouttime});
         



 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no results found");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel model = (DefaultTableModel)
jTable1.getModel();
         int rows=model.getRowCount();
 if (rows>0)
 {
 for (int i=0; i<rows; i++)
model.removeRow(0); 
 }
        String empid=t1.getText();
        String fstname= "";
        String lstname="";
        String name="";
        String logindate;
        String logintime;
        String logoutdate;
        String logouttime;
        
        
          try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from teacher where empid ='"+empid+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
              fstname= rs.getString("fstname");
              lstname= rs.getString("lstname");
               empid = rs.getString("empid");

          
         



 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no name");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
         
        
        
         
        name= fstname+" "+lstname;
        
        
        
        
        
         try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from login where empid='"+empid+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
            
               logindate= rs.getString("logindate");
               logintime= rs.getString("logintime");
               logoutdate= rs.getString("logoutdate");
               logouttime= rs.getString("logouttime");
             

          model.addRow( new Object[]{empid,name,logindate,logintime,logoutdate,logouttime});
         



 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no results found");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }
         
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)
jTable1.getModel(); 
        int rows=model.getRowCount();
 if (rows>0)
 {
 for (int i=0; i<rows; i++)
model.removeRow(0); 
 }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
        t1.requestFocus();
        t1.setEnabled(true);
        t1.setText("");
    }//GEN-LAST:event_t1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(session_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(session_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(session_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(session_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new session_history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
