
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class student_update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public student_update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        d1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        d2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t13 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        d3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        t16 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        m = new javax.swing.JRadioButton();
        t18 = new javax.swing.JTextField();
        f = new javax.swing.JRadioButton();
        t19 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox<>();
        c4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-", " " }));

        jLabel2.setText("Last name");

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED", "BLUE", "GREEN", "YELLOW" }));

        jLabel4.setText("or");

        d1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        jLabel5.setText("and press enter");

        d2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", " February", " March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel6.setText("class");

        t13.setColumns(20);
        t13.setRows(5);
        jScrollPane1.setViewportView(t13);

        jLabel7.setText("sec");

        jLabel8.setText("dob");

        jLabel9.setText("blood group");

        d3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        jLabel10.setText("house");

        jLabel11.setText("fname");

        jLabel12.setText("mname");

        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.setText("enter srno. of student");
        t4.setEnabled(false);
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        jLabel13.setText("address");

        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t5.setText("Enter aadhar card no.");
        t5.setEnabled(false);
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t5MouseClicked(evt);
            }
        });
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });

        jLabel14.setText("occupation f");

        jLabel15.setText("occupation m");

        jLabel16.setText("mob father");

        jLabel17.setText("mob mother");

        jLabel18.setText("email");

        jLabel19.setText("mode of transport");

        t16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t16KeyTyped(evt);
            }
        });

        t17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t17KeyTyped(evt);
            }
        });

        buttonGroup1.add(m);
        m.setText("male");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        buttonGroup1.add(f);
        f.setText("female");

        t19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t19ActionPerformed(evt);
            }
        });

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(42, 42, 42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(53, 53, 53)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)))
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(f))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(61, 61, 61))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(m)
                    .addComponent(f)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void t19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
     




   
        String id="1";
      String fstname = t1.getText();
      String lstname = t2.getText();
      String gender="";
      String srno = t4.getText();
      String aadhar = t5.getText();
      String clas ;
      String sec ;
      String dob;
      String bg;
      String house;
      String fname = t11.getText();
      String mname = t12.getText();
      String address= t13.getText();
      String occupationf = t14.getText();
      String occupationm = t15.getText();
      String mobf = t16.getText();
      String mobm = t17.getText();
      String email = t18.getText();
      String mod = t19.getText();
      String day;
      String month;
      String year;
      String month1;
      String subject="";
      int mon=0;
      int clas1=0;
    
      if(m.isSelected()==true)
     {
     gender ="M";
     }
     else if(f.isSelected()==true)
     {
     gender ="F";
     
     }
     else
     {
     javax.swing.JOptionPane.showMessageDialog(this,"choose the gender of student");
     }
  
     clas1 = c1.getSelectedIndex()+1;
     clas=""+clas1;
     day= (String) d1.getSelectedItem();
     
     mon= d2.getSelectedIndex()+1;
    month1 = ""+mon; 
    
    int i=month1.length();
    if(i<=1)
    {
    month =""+"0"+month1;
    
    
    }
    else {
    month=""+month1;
    }
    year = (String) d3.getSelectedItem();
     dob= ""+year+month+day;
     
     bg= (String) c2.getSelectedItem();
    house =(String) c3.getSelectedItem();
     
     
     
    sec= (String) c4.getSelectedItem();
       try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update STUDENT set id =700,fstname='"+fstname+"',lstname='"+lstname+"',gender='"+gender+"',srno='"+srno+"',aadhar='"+aadhar+"',class='"+clas+"',sec='"+sec+"',dob='"+dob+"',bg='"+bg+"',house='"+house+"',fname='"+fname+"',mname='"+mname+"',address='"+address+"',occupationf='"+occupationf+"',occupationm='"+occupationm+"',mobf='"+mobf+"',mobm='"+mobm+"',email='"+email+"',mot='"+mod+"' where srno='"+srno+"';";
                    stmt.executeUpdate(query);
                     t1.setText("");
         t2.setText("");
         
         t4.setText("");
         t5.setText("");
         buttonGroup1.clearSelection();
        
          t1.setText("");
         t2.setText("");
         t11.setText("");
         t4.setText("");
         t5.setText("");
         t12.setText("");
         t13.setText("");
         t14.setText("");
         t15.setText("");
         t17.setText("");
         t18.setText("");
         t19.setText("");
         
         
         d1.setSelectedIndex(0);
         d2.setSelectedIndex(0);
         d3.setSelectedIndex(0);
         c4.setSelectedIndex(0);
         c3.setSelectedIndex(0);
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
       
       
        
   
       
            
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_c1ActionPerformed

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        // TODO add your handling code here:
        String con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t5KeyTyped

    private void t16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t16KeyTyped
        // TODO add your handling code here:
        String con_len=t16.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==10)
           evt.consume();
    }//GEN-LAST:event_t16KeyTyped

    private void t17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t17KeyTyped
        // TODO add your handling code here:
        String con_len=t17.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==10)
           evt.consume();
    }//GEN-LAST:event_t17KeyTyped

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
          String id="";
        String fstname = t1.getText();
        String lstname = t2.getText();
        String gender="";
        String srno = t4.getText();
        String aadhar = t5.getText();
        String clas ;
        String sec ;
        String dob;
        String bg;
        String house="";
        String fname = t11.getText();
        String mname = t12.getText();
        String address= t13.getText();
        String occupationf = t14.getText();
        String occupationm = t15.getText();
        String mobf = t16.getText();
        String mobm = t17.getText();
        String email = t18.getText();
        String mod = t19.getText();
    String subject="";
     
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from student where srno='"+srno+"'or aadhar='"+aadhar+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
                 
                 
                 
                 
         id= rs.getString("id");
       fstname = rs.getString("fstname");
        lstname = rs.getString("lstname");
        gender=rs.getString("gender");
        srno = rs.getString("srno");
        aadhar = rs.getString("aadhar");
        clas =rs.getString("class");
        sec =     rs.getString("sec");
  dob= rs.getString("dob");
       bg=rs.getString("bg");
     house=rs.getString("house");
         fname =rs.getString("fname");
         mname = rs.getString("mname");
         address= rs.getString("address");
         occupationf = rs.getString("occupationf");
         occupationm = rs.getString("occupationm");
         mobf = rs.getString("mobf");
         mobm = rs.getString("mobm");
         email = rs.getString("email");
         mod = rs.getString("mot");
         
         if(gender.equalsIgnoreCase("m"))
         {
         m.setSelected(true);
         }
         else
         {
         f.setSelected(true);
         }
          
         
        int clas1= Integer.parseInt(clas)-1;
        c1.setSelectedIndex(clas1);
        c4.setSelectedItem(sec);
        String dob1=dob.substring(0,4);
        String dob2=dob.substring(5,7);
        String dob3=dob.substring(8,10);
       int dob4= Integer.parseInt(dob3)-1;
        d1.setSelectedIndex(dob4);
      int dob5=Integer.parseInt(dob2)-1;
        d2.setSelectedIndex(dob5);
        d3.setSelectedItem(dob1);
System.out.println(dob1);
System.out.println(dob2);
System.out.println(dob3);
c2.setSelectedItem(bg);
c3.setSelectedItem(house);


t1.setText(fstname);
t2.setText(lstname);
t4.setText(srno);
t5.setText(aadhar);
t11.setText(fname);
t12.setText(mname);
t13.setText(address);
t14.setText(occupationf);
t15.setText(occupationm);
t16.setText(mobf);
t17.setText(mobm);
t18.setText(email);
t19.setText(mod);



 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no such name");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        t5.setEnabled(true);

                      








    }//GEN-LAST:event_t4ActionPerformed

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
        // TODO add your handling code here:
        t4.requestFocus();
        t4.setEnabled(true);
        t4.setText("");
    }//GEN-LAST:event_t4MouseClicked

    private void t5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseClicked
        // TODO add your handling code here:
        t5.requestFocus();
        t5.setEnabled(true);
        t5.setText("");
    }//GEN-LAST:event_t5MouseClicked

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
               String id="";
        String fstname = t1.getText();
        String lstname = t2.getText();
        String gender="";
        String srno = t4.getText();
        String aadhar = t5.getText();
        String clas ;
        String sec ;
        String dob;
        String bg;
        String house="";
        String fname = t11.getText();
        String mname = t12.getText();
        String address= t13.getText();
        String occupationf = t14.getText();
        String occupationm = t15.getText();
        String mobf = t16.getText();
        String mobm = t17.getText();
        String email = t18.getText();
        String mod = t19.getText();
    String subject="";
     
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from student where srno='"+srno+"'or aadhar='"+aadhar+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
                 
                 
                 
                 
         id= rs.getString("id");
       fstname = rs.getString("fstname");
        lstname = rs.getString("lstname");
        gender=rs.getString("gender");
        srno = rs.getString("srno");
        aadhar = rs.getString("aadhar");
        clas =rs.getString("class");
        sec =     rs.getString("sec");
  dob= rs.getString("dob");
       bg=rs.getString("bg");
     house=rs.getString("house");
         fname =rs.getString("fname");
         mname = rs.getString("mname");
         address= rs.getString("address");
         occupationf = rs.getString("occupationf");
         occupationm = rs.getString("occupationm");
         mobf = rs.getString("mobf");
         mobm = rs.getString("mobm");
         email = rs.getString("email");
         mod = rs.getString("mot");
         
         if(gender.equalsIgnoreCase("m"))
         {
         m.setSelected(true);
         }
         else
         {
         f.setSelected(true);
         }
          
         
        int clas1= Integer.parseInt(clas)-1;
        c1.setSelectedIndex(clas1);
        c4.setSelectedItem(sec);
        String dob1=dob.substring(0,4);
        String dob2=dob.substring(5,7);
        String dob3=dob.substring(8,10);
       int dob4= Integer.parseInt(dob3)-1;
        d1.setSelectedIndex(dob4);
      int dob5=Integer.parseInt(dob2)-1;
        d2.setSelectedIndex(dob5);
        d3.setSelectedItem(dob1);
System.out.println(dob1);
System.out.println(dob2);
System.out.println(dob3);
c2.setSelectedItem(bg);
c3.setSelectedItem(house);


t1.setText(fstname);
t2.setText(lstname);
t4.setText(srno);
t5.setText(aadhar);
t11.setText(fname);
t12.setText(mname);
t13.setText(address);
t14.setText(occupationf);
t15.setText(occupationm);
t16.setText(mobf);
t17.setText(mobm);
t18.setText(email);
t19.setText(mod);




 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no such name");
         }     
     
     
     
     
        }
        catch(Exception e)

        {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        t4.setEnabled(true);

                      


    }//GEN-LAST:event_t5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JComboBox<String> d1;
    private javax.swing.JComboBox<String> d2;
    private javax.swing.JComboBox<String> d3;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton m;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextArea t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
