
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class subject_change extends javax.swing.JFrame {

    /**
     * Creates new form subject_change
     */
    public subject_change() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("Enter the Srno and press enter");
        t1.setEnabled(false);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(30, 80, 191, 38);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science (maths)", "Science (biology)", "commerce", "humanities" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(100, 250, 111, 20);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 90, 50, 14);

        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t2);
        t2.setBounds(330, 80, 165, 38);

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical education", "Computer Science", "Informatic Practices", "Music", "Engineering Graphics", "Home Science", "biotechonology", "fashion studies", "Fine arts" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(250, 250, 130, 20);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 250, 67, 23);

        jLabel3.setText("Class");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 160, 26, 14);

        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t3);
        t3.setBounds(300, 150, 88, 38);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 35, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        if (c1.getSelectedIndex()==0)
        {
            c2.removeAllItems();
            c2.addItem("Physical education");
            c2.addItem("Computer Science");
            c2.addItem("Informatic Practices");
            c2.addItem("Music");
            c2.addItem("Engineering Graphics");
            c2.addItem("Home Science");
            c2.addItem("Biotechonology");
            c2.addItem("Fashion studies");
            c2.addItem("Fine arts ");

        }

        if(c1.getSelectedIndex()==1)
        {
            c2.removeAllItems();
            c2.addItem("Maths");

            c2.addItem("Informatic Practices");
            c2.addItem("Music");

            c2.addItem("Home Science");
            c2.addItem("Biotechonology");
            c2.addItem("Fashion studies");
            c2.addItem("Fine arts ");

        }

        if(c1.getSelectedIndex()==2)
        {

            c2.removeAllItems();
            c2.addItem("Legal studies");
            c2.addItem("entrepreneurship");
            c2.addItem("Informatic Practices");
            c2.addItem("Music");
            c2.addItem("maths");
            c2.addItem("Home Science");
            
            c2.addItem("Fashion studies");
            c2.addItem("Fine arts ");

        }

        if(c1.getSelectedIndex()==3)
        {
            c2.removeAllItems();
            c2.addItem("Legal studies");
            c2.addItem("entrepreneurship");
            c2.addItem("Informatic Practices");
            c2.addItem("Music");
            c2.addItem("maths");
            c2.addItem("Home Science");
           
            c2.addItem("Fashion studies");
            c2.addItem("Fine arts ");

        }

    }//GEN-LAST:event_c1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String subject;
        String optional;
        subject = (String) c1.getSelectedItem();
        optional= (String) c2.getSelectedItem();
        String srno=t1.getText();

        try

        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
                "root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="update subject set subject='"+subject+"',optional='"+optional+"' where srno='"+srno+"';";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "subject updated succesfully");

        }
        
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
        t1.requestFocus();
        t1.setText("");
        t1.setEnabled(true);
    }//GEN-LAST:event_t1MouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        //        this.setExtendedState(MAXIMIZED_BOTH);
        String fstname="";
        String lstname="";
        String clas="";
        String sec="";
        String srno= t1.getText();
        String subject="";
        String optional="";
        
        
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from student where srno='"+srno+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
                 
                 
                 
                 
         
       fstname = rs.getString("fstname");
        lstname = rs.getString("lstname");
        
        srno = rs.getString("srno");
        
        clas =rs.getString("class");
        sec =     rs.getString("sec");
 
         
          
         
       
Found++;


             }
              
       
     
     t2.setText(fstname+" "+lstname);
     t1.setText(srno);
     t3.setText(clas+" "+sec);
     if(Found==0)
     {
     JOptionPane.showMessageDialog(this, "no srno found");
     }
     
     
     
        }
        catch(Exception e)

        {

            JOptionPane.showMessageDialog(this, e.getMessage());

   
        
    }      
        
        
       
        
         try
        {
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con= (java.sql.Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            java.sql.Statement stmt = (java.sql.Statement) con.createStatement();

            String query="select * from subject where srno= '"+srno+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
               subject= rs.getString("subject");
               optional= rs.getString("optional");
               
               
               
             }
              
         
     
     
     
     
        }
        catch(Exception e)

        {
                 

        JOptionPane.showMessageDialog(this, e.getMessage());
        }
         c1.setSelectedItem(subject);
         c2.setSelectedItem(optional);
        
    }//GEN-LAST:event_t1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subject_change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subject_change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subject_change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subject_change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subject_change().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    // End of variables declaration//GEN-END:variables
}
