
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class subject_add extends javax.swing.JFrame {

    /**
     * Creates new form subject_add
     */
    public subject_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        c2 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Sr. No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(44, 90, 100, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(277, 90, 90, 20);

        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t2);
        t2.setBounds(350, 80, 124, 35);

        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t3);
        t3.setBounds(610, 80, 85, 34);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Class");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 80, 90, 20);

        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 330, 140, 50);

        c2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical education", "Computer Science", "Informatic Practices", "Music", "Engineering Graphics", "Home Science", "biotechonology", "fashion studies", "Fine arts" }));
        getContentPane().add(c2);
        c2.setBounds(340, 210, 270, 50);

        c1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science (maths)", "Science (biology)", "commerce", "humanities" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(60, 210, 230, 50);

        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(t1);
        t1.setBounds(130, 80, 94, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chairs-in-empty-school-room.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-320, -210, 1239, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
        String fstname="";
        String lstname="";
        String clas="";
        String sec="";
        String srno= student.sno;
        
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm","root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from student where srno='"+srno+"';";
     ResultSet rs= stmt.executeQuery(query);

int Found=0;
         while(rs.next()) 
                    
             {
                 
                 
                 
                 
         
       fstname = rs.getString("fstname");
        lstname = rs.getString("lstname");
        
        srno = rs.getString("srno");
        
        clas =rs.getString("class");
        sec =     rs.getString("sec");
 
         
          
         
       



             }
              
       
     
     t2.setText(fstname+" "+lstname);
     t1.setText(srno);
     t3.setText(clas+" "+sec);
     
     
     
        }
        catch(Exception e)

        {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String subject;
        String optional;
        subject = (String) c1.getSelectedItem();
        optional= (String) c2.getSelectedItem();
        String srno=student.sno;
        
        try
             
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    Statement stmt = (Statement) con.createStatement();
                    
                    String query="insert into subject values('"+srno+"','"+subject+"','"+optional+"');";
                    stmt.executeUpdate(query);
                    
        }
        catch(Exception e)
            
        {
            
             javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
       
        
     
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        if (c1.getSelectedIndex()==0)
                {
              c2.removeAllItems();
              c2.addItem("Physical education");
              c2.addItem("Computer Science");
              c2.addItem("Informatic Practices");
              c2.addItem("Music");
              c2.addItem("Engineering Graphics");
              c2.addItem("Home Science");
              c2.addItem("Biotechonology");
              c2.addItem("Fashion studies");
              c2.addItem("Fine arts ");
              
                
                }
        
        if(c1.getSelectedIndex()==1)
        {
        c2.removeAllItems();
              c2.addItem("Maths");
             
              c2.addItem("Informatic Practices");
              c2.addItem("Music");
            
              c2.addItem("Home Science");
              c2.addItem("Biotechonology");
              c2.addItem("Fashion studies");
              c2.addItem("Fine arts ");
              
              
        
        }
        
        if(c1.getSelectedIndex()==2)
        {
        
        c2.removeAllItems();
              c2.addItem("Legal studies");
              c2.addItem("entrepreneurship");
              c2.addItem("Informatic Practices");
              c2.addItem("Music");
              c2.addItem("maths");
              c2.addItem("Home Science");
           
              c2.addItem("Fashion studies");
              c2.addItem("Fine arts ");
              
              
              
        
        
        }
        
        if(c1.getSelectedIndex()==3)
        {
          c2.removeAllItems();
              c2.addItem("Legal studies");
              c2.addItem("entrepreneurship");
              c2.addItem("Informatic Practices");
              c2.addItem("Music");
              c2.addItem("maths");
              c2.addItem("Home Science");
             
              c2.addItem("Fashion studies");
              c2.addItem("Fine arts ");
              
              
        
        
        }
        
     
        
    }//GEN-LAST:event_c1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subject_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subject_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subject_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subject_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subject_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    // End of variables declaration//GEN-END:variables
}
