
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class teacher extends javax.swing.JFrame {

    /**
     * Creates new form teacher
     */
    public teacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        d3 = new javax.swing.JComboBox<>();
        d2 = new javax.swing.JComboBox<>();
        d1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 960, 1054, 561);

        jLabel1.setText("empid");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 110, 30, 14);
        getContentPane().add(t1);
        t1.setBounds(240, 110, 135, 20);

        jLabel2.setText("first name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 110, 50, 14);

        jLabel3.setText("last name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 110, 49, 14);
        getContentPane().add(t3);
        t3.setBounds(730, 110, 135, 20);
        getContentPane().add(t5);
        t5.setBounds(730, 190, 135, 20);

        jLabel6.setText("subject");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 190, 36, 14);

        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(510, 190, 135, 20);

        jLabel5.setText("aadhar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 190, 34, 14);

        d3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        getContentPane().add(d3);
        d3.setBounds(330, 190, 50, 20);

        d2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", " February", " March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(d2);
        d2.setBounds(240, 190, 79, 20);

        d1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        getContentPane().add(d1);
        d1.setBounds(180, 190, 38, 20);

        jLabel4.setText("date of birth");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 190, 61, 14);

        jLabel7.setText("Designation");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 280, 59, 14);
        getContentPane().add(t6);
        t6.setBounds(220, 270, 135, 20);

        jLabel8.setText("salary");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 280, 29, 14);
        getContentPane().add(t7);
        t7.setBounds(510, 270, 135, 20);

        jLabel9.setText("mobile");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(680, 290, 33, 14);

        t8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t8KeyTyped(evt);
            }
        });
        getContentPane().add(t8);
        t8.setBounds(730, 280, 135, 20);
        getContentPane().add(t9);
        t9.setBounds(750, 370, 130, 20);

        jLabel12.setText("father name");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(680, 370, 60, 14);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE", "MARRIED", "DIVORCED" }));
        getContentPane().add(c1);
        c1.setBounds(510, 360, 81, 20);

        jLabel11.setText("marital status");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 360, 69, 14);

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 340, 166, 63);

        buttonGroup1.add(r2);
        r2.setText("female");
        getContentPane().add(r2);
        r2.setBounds(570, 420, 59, 23);

        buttonGroup1.add(r1);
        r1.setText("male");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(490, 420, 49, 23);

        jLabel14.setText("gender");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(420, 420, 34, 14);

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED", "GREEN", "BLUE", "YELLOW" }));
        getContentPane().add(c2);
        c2.setBounds(220, 420, 68, 20);

        jLabel10.setText("address");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 350, 39, 14);

        jLabel13.setText("house");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(150, 420, 29, 14);

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 500, 51, 23);
        getContentPane().add(t2);
        t2.setBounds(510, 110, 135, 20);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnuD4O.jpeg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 10, 1069, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String empid= t1.getText();
        String fstname= t2.getText();
        String lstname= t3.getText();
        String dob;
        String aadhar= t4.getText();
        String subject= t5.getText();
        String post= t6.getText();
        String salary= t7.getText();
        String mobile= t8.getText();
       String address= ta1.getText();
       String mstatus;
       String fname= t9.getText();
       String house;
       String gender="";
       String month;
       String day= (String) d1.getSelectedItem();
         int mon     = d2.getSelectedIndex()+1;
         String mon1=""+mon;
         int l= mon1.length();
         if(l<=1)
         {
         month= "0"+mon1;
         
         
         }
               
         else{
         month= mon1;
         
         }
        String year= (String) d3.getSelectedItem();
        dob=year+month+day;
        mstatus= (String) c1.getSelectedItem();
        
        house = (String) c2.getSelectedItem();
        
        if(r1.isSelected()==true)
        {
        
        gender="M";
        
            
        }
        else if(r2.isSelected()==true)
        {
        gender="F";
        
        
        }
        
        
        
        
        
         try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    Statement stmt = (Statement) con.createStatement();
                    
                    String query="insert into teacher values(1,'"+empid+"','"+fstname+"','"+lstname+"','"+dob+"','"+aadhar+"','"+subject+"','"+post+"','"+salary+"','"+mobile+"','"+address+"','"+mstatus+"','"+fname+"','"+house+"','"+gender+"');";
                    stmt.executeUpdate(query);
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
         t1.setText("");
         t2.setText("");
         t3.setText("");
         t4.setText("");
         t5.setText("");
         t6.setText("");
         t7.setText("");
         t8.setText("");
         t9.setText("");
         ta1.setText("");
         buttonGroup1.clearSelection();
         c1.setSelectedIndex(0);
         c2.setSelectedIndex(0);
         d1.setSelectedIndex(0);
         d2.setSelectedIndex(0);
         d3.setSelectedIndex(0);


         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:
        String con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    }//GEN-LAST:event_t4KeyTyped

    private void t8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyTyped
        // TODO add your handling code here:
        String con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==10)
           evt.consume();
    }//GEN-LAST:event_t8KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> d1;
    private javax.swing.JComboBox<String> d2;
    private javax.swing.JComboBox<String> d3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
