
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRAKHAR
 */
public class teacher_update extends javax.swing.JFrame {

    /**
     * Creates new form tupdate
     */
    public teacher_update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        d1 = new javax.swing.JComboBox<String>();
        d2 = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        d3 = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox<String>();
        c2 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        t8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t8KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t8KeyTyped(evt);
            }
        });

        jLabel14.setText("gender");

        r1.setText("male");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setText("female");

        d1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        d2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", " February", " March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel9.setText("mobile");

        d3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        jLabel10.setText("address");

        jLabel11.setText("marital status");

        jLabel12.setText("father name");

        jLabel13.setText("house");

        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("Enter Employee id ");
        t1.setEnabled(false);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.setText("Enter Aadhar Card no.");
        t4.setEnabled(false);
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });

        jLabel1.setText("or");

        jLabel2.setText("first name");

        jLabel3.setText("last name");

        jLabel4.setText("date of birth");

        jLabel5.setText("and press enter");

        jLabel6.setText("subject");

        jLabel7.setText("post");

        jLabel8.setText("salary");

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SINGLE", "MARRIED", "DIVORCED" }));

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RED", "GREEN", "BLUE", "YELLOW" }));

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel13)
                .addGap(67, 67, 67)
                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(r1)
                .addGap(62, 62, 62)
                .addComponent(r2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(65, 65, 65)
                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(r1)
                            .addComponent(r2)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         String empid= t1.getText();
        String fstname= t2.getText();
        String lstname= t3.getText();
        String dob;
        String aadhar= t4.getText();
        String subject= t5.getText();
        String post= t6.getText();
        String salary= t7.getText();
        String mobile= t8.getText();
       String address= ta1.getText();
       String mstatus;
       String fname= t9.getText();
       String house;
       String gender="";
       String month;
       String day= (String) d1.getSelectedItem();
         int mon     = d2.getSelectedIndex()+1;
         String mon1=""+mon;
         int l= mon1.length();
         if(l<=1)
         {
         month= "0"+mon1;
         
         
         }
               
         else{
         month= mon1;
         
         }
        String year= (String) d3.getSelectedItem();
        dob=year+month+day;
        mstatus= (String) c1.getSelectedItem();
        
        house = (String) c2.getSelectedItem();
        
        if(r1.isSelected()==true)
        {
        
        gender="M";
        
            
        }
        else if(r2.isSelected()==true)
        {
        gender="F";
        
        
        }
        
        
        
        
        
         try
        {
            Class.forName("java.sql.DriverManager");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
 "root", "window");
                    com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                    
                    String query="update teacher set empid='"+empid+"',fstname='"+fstname+"',lstname='"+lstname+"',dob='"+dob+"',aadhar='"+aadhar+"',subject='"+subject+"',post='"+post+"',salary='"+salary+"',mob='"+mobile+"',address='"+address+"',mstatus='"+mstatus+"',fname='"+fname+"',house='"+house+"',gender='"+gender+"' where empid='"+empid+"';";
                    stmt.executeUpdate(query);
                    
        }
        catch(Exception e)
            
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_t8KeyPressed

    private void t8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyTyped
        // TODO add your handling code here:
        
          String con_len=t8.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==10)
           evt.consume();
    }//GEN-LAST:event_t8KeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       t1.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
        t1.requestFocus();
        t1.setText("");
        t1.setEnabled(true);
    }//GEN-LAST:event_t1MouseClicked

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
        // TODO add your handling code here:
        t4.requestFocus();
        t4.setText("");
        t4.setEnabled(true);
    }//GEN-LAST:event_t4MouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        
         String id="";
        String empid= t1.getText();
        String fstname= t2.getText();
        String lstname= t3.getText();
        String dob;
        String aadhar= t4.getText();
        String subject= t5.getText();
        String post= t6.getText();
        String salary= t7.getText();
        String mobile= t8.getText();
        String address= ta1.getText();
        String mstatus;
        String fname= t9.getText();
        String house;
        String gender="";
 String year= (String) d3.getSelectedItem();


        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
                "root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from teacher where empid='"+empid+"'or aadhar='"+aadhar+"';";
          ResultSet rs=  stmt.executeQuery(query);

          
          
          int Found=0;
         while(rs.next()) 
                    
             {
             
             
               id= rs.getString("id");
                 empid= rs.getString("empid");
       fstname = rs.getString("fstname");
        lstname = rs.getString("lstname");
        gender=rs.getString("gender");
        
         dob= rs.getString("dob");
         aadhar=rs.getString("aadhar");
          subject=rs.getString("subject");
           post=rs.getString("post");
            salary=rs.getString("salary");
       mobile = rs.getString("mob");
        address=rs.getString("address");
      mstatus=rs.getString("mstatus");
        house=rs.getString("house");
     
         fname =rs.getString("fname");
         
         
         if(gender.equalsIgnoreCase("m"))
         {
         r1.setSelected(true);
         
         }
else
         {
         r2.setSelected(true);
         
         }
         
         String dob1= dob.substring(0,4);
         String dob2=dob.substring(5,7);
         String dob3=dob.substring(8,10);
         
         d3.setSelectedItem(dob1);
         d1.setSelectedItem(dob3);
         int i = Integer.parseInt(dob2)-1;
         d2.setSelectedIndex(i);
         
         c1.setSelectedItem(mstatus);
         c2.setSelectedItem(house);
         
         
         t1.setText(empid);
         t2.setText(fstname);
         t3.setText(lstname);
t4.setText(aadhar);
t5.setText(subject);
t6.setText(post);
t7.setText(salary);
t8.setText(mobile);
ta1.setText(address);
t9.setText(fname);
         
         
             
            
 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no Employee Found");
         }     
     
     
     
     
          
        }
        
        
        
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }

       t4.setEnabled(true);
    }//GEN-LAST:event_t1ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
        
          
         String id="";
        String empid= t1.getText();
        String fstname= t2.getText();
        String lstname= t3.getText();
        String dob;
        String aadhar= t4.getText();
        String subject= t5.getText();
        String post= t6.getText();
        String salary= t7.getText();
        String mobile= t8.getText();
        String address= ta1.getText();
        String mstatus;
        String fname= t9.getText();
        String house;
        String gender="";
 String year= (String) d3.getSelectedItem();


        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/schm",
                "root", "window");
            Statement stmt = (Statement) con.createStatement();

            String query="select * from teacher where empid='"+empid+"'or aadhar='"+aadhar+"';";
          ResultSet rs=  stmt.executeQuery(query);

          
          
          int Found=0;
         while(rs.next()) 
                    
             {
             
             
               id= rs.getString("id");
                 empid= rs.getString("empid");
       fstname = rs.getString("fstname");
        lstname = rs.getString("lstname");
        gender=rs.getString("gender");
        
         dob= rs.getString("dob");
         aadhar=rs.getString("aadhar");
          subject=rs.getString("subject");
           post=rs.getString("post");
            salary=rs.getString("salary");
       mobile = rs.getString("mob");
        address=rs.getString("address");
      mstatus=rs.getString("mstatus");
        house=rs.getString("house");
     
         fname =rs.getString("fname");
         
         
         if(gender.equalsIgnoreCase("m"))
         {
         r1.setSelected(true);
         
         }
else
         {
         r2.setSelected(true);
         
         }
         
         String dob1= dob.substring(0,4);
         String dob2=dob.substring(5,7);
         String dob3=dob.substring(8,10);
         
         d3.setSelectedItem(dob1);
         d1.setSelectedItem(dob3);
         int i = Integer.parseInt(dob2)-1;
         d2.setSelectedIndex(i);
         
         c1.setSelectedItem(mstatus);
         c2.setSelectedItem(house);
         
         
         t1.setText(empid);
         t2.setText(fstname);
         t3.setText(lstname);
t4.setText(aadhar);
t5.setText(subject);
t6.setText(post);
t7.setText(salary);
t8.setText(mobile);
ta1.setText(address);
t9.setText(fname);
         
         
             
            
 Found++; 
             }
              
         if(Found==0)
         {
         
         javax.swing.JOptionPane.showMessageDialog(this, "no Employee Found");
         }     
     
     
     
     
          
        }
        
        
        
        catch(Exception e)

        {

            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

        }

       t1.setEnabled(true);
    }//GEN-LAST:event_t4ActionPerformed

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:
          String con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
       if (con_len.length()==12)
           evt.consume();
    
    }//GEN-LAST:event_t4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> d1;
    private javax.swing.JComboBox<String> d2;
    private javax.swing.JComboBox<String> d3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
