
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STUDENT
 */
public class update_and_search_vendor extends javax.swing.JFrame {

    /**
     * Creates new form update_and_search_vendor
     */
    public update_and_search_vendor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        t2.setEditable(false);
        getContentPane().add(t2);
        t2.setBounds(220, 210, 247, 20);

        jLabel1.setText("vendor id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 150, 69, 32);

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(220, 160, 247, 20);

        jButton5.setText("search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(530, 160, 65, 23);

        t3.setEditable(false);
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(220, 260, 247, 20);

        jLabel5.setText("Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 250, 99, 32);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 200, 99, 32);

        jLabel6.setText("address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 300, 88, 32);

        t4.setEditable(false);
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(220, 310, 247, 20);

        jLabel8.setText("email id");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 360, 88, 32);

        t5.setEditable(false);
        getContentPane().add(t5);
        t5.setBounds(220, 360, 247, 20);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 420, 55, 23);

        jButton6.setText("update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(190, 420, 67, 23);

        b3.setText("delete");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(280, 420, 63, 23);

        jButton4.setText("reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 420, 57, 23);

        jButton3.setText("exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 420, 51, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kzi1bp.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-180, -130, 982, 708);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new a1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String id,cname,cnum,addr,email;//cname is name ,cnum is contact no. and addr is address
        id=t1.getText();
        cname=t2.getText();
        cnum=t3.getText();
        addr=t4.getText();
        email=t5.getText();

        if (id.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"vendor id not entered!!!");
        }
        else if (cname.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Vendor name  not entered!!!");
        }
        else if(cnum.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Contact Number not entered!!!");
        }
        else if (cnum.length()!=10)
        {
            JOptionPane.showMessageDialog(this,"Incorrect Number!!!");
            t3.setText("");
        }
        else if(addr.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Address not entered!!!");
        }
        else if(email.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Email Id not entered!!!");
        }

        else
        {
            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                String query="Update vendor set vendor_name='"+cname+"',vendor_number='"+cnum+"',address='"+addr+"',email_id='"+email+"');";
                stm.executeUpdate(query);

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");

            t2.setEditable(false);
            t3.setEditable(false);
            t4.setEditable(false);
            t5.setEditable(false);

            t1.requestFocus();
            b3.setEnabled(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        String id,cname,cnum,addr,email;//cname is name ,cnum is contact no. and addr is address
        id=t1.getText();
        cname=t2.getText();
        cnum=t3.getText();
        addr=t4.getText();
        email=t5.getText();

        if (id.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"vendor id not entered!!!");
        }
        else if (cname.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Vendor name  not entered!!!");
        }
        else if(cnum.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Contact Number not entered!!!");
        } else if(addr.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Address not entered!!!");
        }
        else if(email.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Email Id not entered!!!");
        }
        else
        {
            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                String query="delete from vendor where vendor_id='"+id+"';";
                stm.executeUpdate(query);

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");

            t2.setEditable(false);
            t3.setEditable(false);
            t4.setEditable(false);
            t5.setEditable(false);

            b3.setEnabled(false);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");

        t2.setEditable(false);
        t3.setEditable(false);
        t4.setEditable(false);
        t5.setEditable(false);

        b3.setEnabled(false);
        t1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id,cname,cnum,addr,email;//cname is name ,cnum is contact no. and addr is address

        id=t1.getText();
        if(id.isEmpty())
        {
            JOptionPane.showMessageDialog (this,"Enter vendor id!!!");
        }
        else
        {
            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                String query="select * from vendor where vendor_id ='"+id+"';";
                ResultSet rs=stm.executeQuery(query);
                if(rs.next())
                {
                    cname=rs.getString("vendor_name");
                    cnum=rs.getString("vendor_number");
                    addr=rs.getString("address");
                    email=rs.getString("email_id");

                    t2.setText(cname);
                    t3.setText(cnum);
                    t4.setText(addr);
                    t5.setText(email);

                    t2.setEditable(true);
                    t3.setEditable(true);
                    t4.setEditable(true);
                    t5.setEditable(true);

                }
                else
                {
                    JOptionPane.showMessageDialog (this, "Sorry! No such Vendor id Exists.");
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
            b3.setEnabled(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        String con_len=t1.getText();//con_len:- Vendorid length
        if (con_len.length()==4)
        evt.consume();
    }//GEN-LAST:event_t1KeyTyped

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
        // TODO add your handling code here:
        String con_len=t3.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'0')||(character >'9'))
        evt.consume();
        if (con_len.length()==10)
        evt.consume();
    }//GEN-LAST:event_t3KeyTyped

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_t4KeyTyped

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_and_search_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_and_search_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_and_search_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_and_search_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_and_search_vendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
