
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STUDENT
 */
public class update_and_search_book extends javax.swing.JFrame {

    /**
     * Creates new form update_and_search_book
     */
    public update_and_search_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<String>();
        t4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("book id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 120, 69, 32);

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(220, 130, 247, 20);

        jButton5.setText("search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 130, 65, 23);

        t2.setEditable(false);
        getContentPane().add(t2);
        t2.setBounds(220, 180, 247, 20);

        jLabel3.setText("Title ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 170, 75, 32);

        jLabel5.setText("Author");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 220, 88, 32);

        jLabel2.setText("volume no.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 270, 96, 32);

        t3.setEditable(false);
        getContentPane().add(t3);
        t3.setBounds(220, 230, 247, 20);

        jLabel6.setText("Publisher");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 320, 88, 32);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volume Number", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        c1.setEnabled(false);
        getContentPane().add(c1);
        c1.setBounds(260, 280, 182, 20);

        t4.setEditable(false);
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(220, 330, 247, 20);

        jLabel8.setText("cost");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 380, 88, 32);

        t5.setEditable(false);
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(220, 380, 247, 20);

        jLabel9.setText("availability");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 430, 88, 32);

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Availability", "Available", "Not-Available" }));
        c2.setEnabled(false);
        getContentPane().add(c2);
        c2.setBounds(220, 440, 182, 20);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 510, 55, 23);

        jButton6.setText("update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(270, 510, 67, 23);

        b3.setText("delete");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(350, 510, 63, 23);

        jButton4.setText("reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(420, 510, 57, 23);

        jButton3.setText("exit");
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 510, 51, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kzi1bp.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-120, -70, 982, 708);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        c1.setSelectedItem("Volume Number");
        c1.setSelectedItem("Availability");

        t2.setEditable(false);
        t3.setEditable(false);
        t4.setEditable(false);
        t5.setEditable(false);
        c2.setEnabled(false);
        c1.setEnabled(false);
        b3.setEnabled(false);

        t1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id,title,author,publ,cost,d,avail;//d is volume_no., publ is publisher and avail is availability
        id=t1.getText();
        if(id.isEmpty())
        {
            JOptionPane.showMessageDialog (this,"Enter book id!!!");
        }
        else
        {
            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                String query="select * from books where book_id ='"+id+"';";
                ResultSet rs=stm.executeQuery(query);
                if(rs.next())
                {
                    title=rs.getString("title");
                    author=rs.getString("author");
                    d=rs.getString("volume");
                    cost=rs.getString("cost");
                    publ=rs.getString("publisher");
                    avail=rs.getString("availability");
                    t2.setText(title);
                    t3.setText(author);
                    c1.setSelectedItem(d);
                    t4.setText(publ);
                    t5.setText(cost);

                    if(avail.equalsIgnoreCase("available"))
                    {
                        c2.setSelectedIndex(1);
                    }
                    if (avail.equalsIgnoreCase("not-available"))
                    {
                        c2.setSelectedIndex(2);
                    }

                    t2.setEditable(true);
                    t3.setEditable(true);
                    t4.setEditable(true);
                    t5.setEditable(true);
                    c2.setEnabled(true);
                    c1.setEnabled(true);

                }
                else
                {
                    JOptionPane.showMessageDialog (this, "Sorry! No such book id Exists.");
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
            b3.setEnabled(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new a1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        String con_len=t1.getText();//con_len:- Vendorid length
        if (con_len.length()==4)
        evt.consume();
    }//GEN-LAST:event_t1KeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String id,title,author,cost,publ,d,avail;//d is volume_no.,publ is publisher and avail is availability
        id=t1.getText();
        title=t2.getText();
        author=t3.getText();
        publ=t4.getText();
        cost=t5.getText();
        d=(String) c1.getSelectedItem();
        avail=(String) c2.getSelectedItem();

        if (id.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"member id not entered!!!");
        }
        else if (title.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Title not entered!!!");
        }
        else if(author.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Author not entered!!!");
        } else if(cost.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Cost not entered!!!");
        }
        else if(publ.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Publisher not entered!!!");
        }
        else if(d.equalsIgnoreCase("Volume Number"))
        {
            JOptionPane.showMessageDialog(this,"Volume Number not entered!!!");
        }
        else if (avail.equalsIgnoreCase("Availability"))
        {
            JOptionPane.showMessageDialog(this,"Availability not entered!!!");
        }

        else
        {
            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                String query="update books set title='"+title+"',author='"+author+"',cost='"+cost+"',volume='"+d+"',publisher='"+publ+"',availability='"+avail+"' where book_id='"+id+"';";
                stm.executeUpdate(query);

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            c1.setSelectedItem("Volume Number");
            c2.setSelectedItem("Availability");

            t2.setEditable(false);
            t3.setEditable(false);
            t4.setEditable(false);
            t5.setEditable(false);
            c2.setEnabled(false);
            c1.setEnabled(false);

            b3.setEnabled(false);
            t1.requestFocus();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_t4KeyTyped

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4KeyPressed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        String id,title,author,cost,publ,d,avail;//d is volume_no.,publ is publisher and avail is availability
        id=t1.getText();
        title=t2.getText();
        author=t3.getText();
        publ=t4.getText();
        cost=t5.getText();
        d=(String) c1.getSelectedItem();
        avail=(String) c2.getSelectedItem();

        if (id.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"member id not entered!!!");
        }
        else if (title.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Title not entered!!!");
        }
        else if(author.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Author not entered!!!");
        } else if(cost.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Cost not entered!!!");
        }
        else if(publ.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Publisher not entered!!!");
        }
        else if(d.equalsIgnoreCase("Volume Number"))
        {
            JOptionPane.showMessageDialog(this,"Volume Number not entered!!!");
        }
        else if (avail.equalsIgnoreCase("Availability"))
        {
            JOptionPane.showMessageDialog(this,"Availability not entered!!!");
        }

        else
        {
            try

            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/schm","root", "window");
                Statement stm = (Statement) conn.createStatement();
                String query="delete from books where book_id='"+id+"';";
                stm.executeUpdate(query);

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            c1.setSelectedItem("Volume Number");
            c2.setSelectedItem("Availabity");

            t2.setEditable(false);
            t3.setEditable(false);
            t4.setEditable(false);
            t5.setEditable(false);
            c2.setEnabled(false);
            c1.setEnabled(false);

            b3.setEnabled(false);
            t1.requestFocus();
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        // TODO add your handling code here:
        String con_len=t5.getText();//con_len:- contact length
        char character=evt.getKeyChar();
        if ((character<'.')||(character >'9'))
        evt.consume();
        if (con_len.length()==10)
        evt.consume();
    }//GEN-LAST:event_t5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_and_search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_and_search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_and_search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_and_search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_and_search_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
